DROP TABLE IF EXISTS variaveis_municipios;

CREATE TABLE variaveis_municipios AS
SELECT
    g.ogc_fid AS gid,
    a.fid AS fid,
    g.geom,
    g.cd_mun::text AS cod_mun,
    COALESCE(a.nm_mun, g.nm_mun) AS nm_mun,
    COALESCE(NULLIF(a.municipio, ''), g.nm_mun || ' (' || g.sigla_uf || ')') AS municipio,
    g.cd_rgi::text AS cd_rgi,
    g.nm_rgi,
    g.cd_rgint::text AS cd_rgint,
    g.nm_rgint,
    g.cd_uf::text AS cd_uf,
    g.nm_uf,
    g.sigla_uf,
    g.cd_regiao::text AS cd_regiao,
    g.nm_regiao,
    g.sigla_rg,
    g.cd_concurb::text AS cd_concurb,
    g.nm_concurb,
    g.area_km2,
    a.pib_total,
    a.impostos_sub,
    a.pib_agro,
    a.pib_industria,
    a.pib_servicos,
    a.pib_adm,
    a.pop_total,
    a.dom_total,
    a.empresas_total,
    a.fundeb_vaaf,
    a.fundeb_vaar,
    a.fundeb_vaat,
    a.fundeb_fpe,
    a.fundeb_fpm,
    a.fundeb_fti,
    a.fundeb_icms,
    a.fundeb_ipi_exp,
    a.fundeb_ipva,
    a.fundeb_itcmd,
    a.fundeb_itr,
    a.esgoto_pop_total_rede,
    a.esgoto_pop_urb_rede,
    a.esgoto_dom_total_rede,
    a.esgoto_dom_urb_rede,
    a.esgoto_dom_total_trat,
    a.esgoto_dom_urb_trat,
    a.vitimas_homicidio_2022,
    a.via_pav_pct,
    a.via_pav_n,
    a.ilum_pub_pct,
    a.ilum_pub_n,
    a.calcada_pct,
    a.calcada_n,
    a.regic_var56,
    a.regic_var57,
    a.regic_var58,
    a.regic_var59,
    a.regic_var60,
    a.regic_var61,
    a.regic_var62,
    a.regic_var63,
    a.regic_var64,
    a.regic_var65,
    a.regic_var66,
    a.plano_diretor,
    a.area_urb_densa_km2,
    a.loteamento_vazio_km2,
    a.vazios_intraurbanos_km2,
    a.demissoes_2025,
    a.ambulatorios_sus_2026_02,
    a.posto_saude,
    a.centro_saude_ubs,
    a.policlinica,
    a.hospital_geral,
    a.hospital_esp,
    a.unidade_mista,
    a.pronto_socorro_geral,
    a.pronto_socorro_esp,
    a.consultorio_isolado,
    a.unidade_movel_fluvial,
    a.clinica_centro_esp,
    a.sadt_isolado,
    a.unidade_movel_terrestre,
    a.unidade_movel_pre_hosp_urg,
    a.farmacia,
    a.vigilancia_saude,
    a.coop_cessao_saude,
    a.centro_parto_normal_isol,
    a.hospital_dia_isol,
    a.lacen,
    a.central_gestao_saude,
    a.hemoterapia_hematologia,
    a.caps,
    a.apoio_saude_familia,
    a.saude_indigena,
    a.pronto_atendimento,
    a.polo_academia_saude,
    a.telessaude,
    a.regulacao_medica_urg,
    a.atencao_domiciliar_homecare,
    a.atencao_regime_residencial,
    a.oficina_ortopedica,
    a.laboratorio_saude_pub,
    a.regulacao_acesso,
    a.notif_capt_distrib_orgaos,
    a.prev_agravos_prom_saude,
    a.central_abastecimento,
    a.centro_imunizacao,
    a.estab_total,
    a.demanda_agua_hum_urb_m3s,
    a.demanda_agua_hum_rur_m3s,
    a.demanda_agua_ind_m3s,
    a.demanda_agua_min_m3s,
    a.demanda_agua_term_m3s,
    a.demanda_agua_animal_m3s,
    a.demanda_agua_irr_m3s,
    a.demanda_agua_total_m3s,
    a.registros_seca_2003_2015,
    a.indice_conectividade,
    a.cobertura_pop_4g5g,
    a.densidade_smp,
    a.hhi_smp,
    a.densidade_scm,
    a.hhi_scm,
    a.adensamento_estacoes,
    a.fibra,
    a.cobertura_area_agricultavel,
    a.desloc_trab_ate_5min_2022,
    a.desloc_trab_6a15min_2022,
    a.desloc_trab_15a30min_2022,
    a.desloc_trab_30a60min_2022,
    a.desloc_trab_1a2h_2022,
    a.desloc_trab_2a4h_2022,
    a.desloc_trab_mais_4h_2022,
    a.transp_trab_pe,
    a.transp_trab_bicicleta,
    a.transp_trab_motocicleta,
    a.transp_trab_automovel,
    a.transp_trab_onibus,
    a.transp_trab_trem_metro,
    a.transp_trab_outros
FROM stg_municipios_geo g
LEFT JOIN stg_variaveis_municipios_attr a
    ON lpad(a.cod_mun::text, 7, '0') = g.cd_mun;

CREATE INDEX idx_variaveis_municipios_geom
ON variaveis_municipios
USING GIST (geom);

CREATE INDEX idx_variaveis_municipios_cod_mun
ON variaveis_municipios (cod_mun);

CREATE INDEX idx_variaveis_municipios_cd_rgi
ON variaveis_municipios (cd_rgi);

CREATE INDEX idx_variaveis_municipios_cd_rgint
ON variaveis_municipios (cd_rgint);
